apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rulemaker
labels:
- includeSelectors: true
  pairs:
    app: rulemaker

resources:
- rulemaker

configMapGenerator:
- name: custom-rules-fragments
  options:
    labels:
      thanos-rules: ""
    disableNameSuffixHash: true
  files:
    - files/ceph.yaml
    - files/storage.yaml

