apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    component: rulemaker

resources:
- deployment.yaml
- rolebinding.yaml
- sa.yaml

configMapGenerator:
- name: rulemaker-scripts
  files:
  - watcher.sh
